export const record_dptchecklist = 'record_dptchecklist'
export const record_empchecklist = 'record_empchecklist'
export const record_noticetitle = 'record_noticetitle'
export const record_noticewriter = 'record_noticewriter'
export const record_noticecontent = 'record_noticecontent'
export const record_token = 'record_token'
export const record_entId = 'record_entId'